[app]
env = "development"
scheme = "http"
host = "127.0.0.1"
port = 8000
version = "0.0.1"

[db]
username = "user"
password = "password"
host = "127.0.0.1"
port = 5432
name = "spenmo"

[log]
level = "debug"